# Generated by Django 4.2.4 on 2023-10-28 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Homepage', '0009_userprofile_alter_book_user'),
        ('Bookphoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.AddField(
            model_name='review',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='review_photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_books',
            field=models.ManyToManyField(blank=True, related_name='users_like', to='Homepage.book'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
