# Generated by Django 4.2.6 on 2023-10-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookphoria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name',
            new_name='username',
        ),
    ]
