# Generated by Django 4.2.6 on 2023-10-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookphoria', '0002_rename_full_name_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
