# Generated by Django 4.2.4 on 2023-10-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookphoria', '0002_remove_review_created_at_review_date_added_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
