# Generated by Django 4.2.4 on 2023-10-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewApp', '0003_remove_review_rate_remove_review_review_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ImageUrl',
        ),
    ]
