# Generated by Django 4.2.4 on 2023-10-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
        ('ReviewApp', '0003_alter_review_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ManyToManyField(related_name='review', to='Homepage.imageurl'),
        ),
    ]
