# Generated by Django 4.2.5 on 2023-10-29 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewApp', '0006_remove_review_photo_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ReviewApp.book'),
            preserve_default=False,
        ),
    ]
