# Generated by Django 4.2.4 on 2023-10-28 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookphoria', '0002_remove_review_created_at_review_date_added_and_more'),
        ('DetailBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bookphoria.userprofile'),
        ),
    ]
