# Generated by Django 4.2.4 on 2023-10-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DetailBook', '0002_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='book',
            name='images',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ImageUrl',
        ),
    ]
