# Generated by Django 4.2.4 on 2023-10-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageurl',
            name='url',
            field=models.TextField(),
        ),
    ]
