# Generated by Django 4.2.6 on 2023-10-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_rename_thumbnail_imageurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
    ]
