# Generated by Django 4.2.6 on 2023-10-24 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_alter_book_authors_alter_book_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_edit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
