# Generated by Django 4.2.6 on 2023-10-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0006_book_last_edit_time_book_publish_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='last_edit_time',
            new_name='user_last_edit_time',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publish_time',
            new_name='user_publish_time',
        ),
    ]
