# Generated by Django 4.2.6 on 2023-10-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0007_rename_last_edit_time_book_user_last_edit_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
