# Generated by Django 4.2.4 on 2023-10-29 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Homepage', '0011_alter_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(related_name='likes_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
